# Generated by Django 3.0 on 2020-01-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameFaqs_Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='body',
            field=models.TextField(default='Body'),
            preserve_default=False,
        ),
    ]
