# Generated by Django 3.0 on 2020-01-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameFaqs_Backend', '0002_message_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfuser',
            name='signature',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gfuser',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
