# Generated by Django 3.0 on 2020-01-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameFaqs_Backend', '0003_auto_20200107_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfuser',
            name='signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gfuser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
