# Generated by Django 3.0 on 2020-01-13 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GameFaqs_Backend', '0004_auto_20200107_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='post_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
