# Generated by Django 3.0 on 2020-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameFaqs_Backend', '0006_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
