# Generated by Django 3.0 on 2020-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameFaqs_Backend', '0007_question_spoiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='spoiler',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
