# Generated by Django 3.0 on 2020-01-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameFaqs_Backend', '0010_auto_20200115_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bnswer',
            new_name='Answer',
        ),
    ]
